name: Ito_paper
version: '${project.version}'
main: net.tv.twitch.chrono_fish.ito_paper.Ito_paper
api-version: '1.20'
description: 'This is a custom plugin for playing "ito".'
commands:
  menu:
    permission: ito_paper.menu
permissions:
  ito_paper.menu:
    description: Permission to use the /menu command
    default: op
