name: Ito_paper
version: '${project.version}'
main: net.tv.twitch.chrono_fish.ito_paper.Ito_paper
api-version: '1.20'
description: 'This is a custom plugin for playing "ito".'
commands:
  menu:
    permission: ito_paper.menu
  ito:
permissions:
  ito_paper.menu:
    default: op
  ito_paper.sign:
    default: op
